name: 'build-rpm-action'
description: 'Build rpm package.'
author: 'jiro4989'
inputs:
  summary:
    description: 'Package summary.'
    required: true
  package:
    description: 'Package name of rpm package.'
    required: true
  package_root:
    description: 'Directory of release files.'
    required: true
  maintainer:
    description: 'Package maintainer name.'
    required: true
  vendor:
    description: 'Package vendor.'
    default: ''
  version:
    description: 'Package version.'
    required: true
  arch:
    description: 'Package architecture.'
    default: 'x86_64'
  desc:
    description: 'Package description.'
    default: ''
  license:
    description: 'Package LICENSE.'
    default: 'MIT'
  post:
    description: 'Package post.'
    default: ''
outputs:
  file_name:
    description: 'File name of resulting .rpm file. This does not contain a debuginfo file.'
  debuginfo_file_name:
    description: 'File name of resulting .rpm debuginfo file.'
runs:
  using: 'docker'
  image: 'docker://jiro4989/build-rpm-action:2.4.0'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
